# Copyright (c) 2026 QST.Corp
# SPDX-License-Identifier: Apache-2.0

# DMA add-on config for qmi8660 sample on STM32U5
CONFIG_DMA=y
CONFIG_DMA_STM32U5=y
CONFIG_SPI_STM32_DMA=y
CONFIG_I2C_STM32_V2_DMA=y
